# nixpacks.toml

[phases.install]
nixpkgs = [
  "nodejs",  # This will use the default/latest version of Node.js available in Nixpkgs
  "yarn"
]
run = """
  yarn install --frozen-lockfile --check-files || yarn install --immutable --check-cache
"""

[phases.build]
run = """
  yarn build
"""

[phases.start]
cmd = "yarn start"
